version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: root
